baseURL = "https://ukozi.com"
title = "ukozi.com"
languageCode = "en"
DefaultContentLanguage = "en" # Change this to change the site's language
theme = "hugo.386"
preserveTaxonomyNames = true

[params]
    # The name to display as main title in the home page
    mainpagetitle = "ukozi | oo-kah-zee | n. a person, thing, or event that curates contentment from putrefied chaos"

    # The subtitle to display under the title in the home page
    mainpagesubtitle = "" 

    # The description of your website. It will be displayed in the home page
    mainpagedesc = "ukozi.com is an anthology of labor and melee."

    # The name to display in the copyright section in the footer
    copyrightname = "Lucas J. Chumley"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    copyrighturl = "https://ukozi.com"

    # Show the "built on Hugo" disclaimer
    showhugo = true

    # Show a CRT screen effect. Default is enabled.
    showcrt = false

    # Urls for social networks
    twitter = "https://twitter.com/theUkozi"
    linkedin = "https://www.linkedin.com/in/lucas-chumley/"
    github = "https://github.com/ukozi"

    # Enables or disables the loading animations. false activates them. Default is false.
    loadfastload = true

    # Sets the speed for the page loading effect. Default is 1.0.
    loadspeedfactor = 1.0

    # Enables or disables the second flyby cursor. Default is false.
    loadonepass = false

[params.copyright]
    name = "Lucas J. Chumley, ukozi.com"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    url = "https://ukozi.com"

    # Text to go before copyright information
    prefix = ""

    # Text to go between copyright and hugo disclaimer (if enabled)
    suffix = ""

[menu]
  # This displays buttons in the navbar to access your contents
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/post/"       # The path can lead to a content folder too.
    weight = 20
  
  [[menu.main]]
  identifier = "Ukozi Static"
  name = "Ukozi Static"
  url = "/ukozi-static/"       # The path can lead to a content folder too.
  weight = 30

[taxonomies]
category = "categories"
tag = "tags"
facet = "facets"


[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true