baseURL = "https://ukozi.com"
title = "Ukozi"
languageCode = "en"
DefaultContentLanguage = "en" # Change this to change the site's language
theme = "hugo.386"
preserveTaxonomyNames = true

[params]
    # The name to display as main title in the home page
    mainpagetitle = "Ukozi.com"

    # The subtitle to display under the title in the home page
    mainpagesubtitle = "|ook-ah-zee| n. a person, place, thing, or event that derives joy from chaos" 

    # The description of your website. It will be displayed in the home page
    mainpagedesc = "Here is a collection of exhibits."

    # The name to display in the copyright section in the footer
    copyrightname = "Ukozi.com"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    copyrighturl = "https://ukozi.com"

    # Show the "built on Hugo" disclaimer
    showhugo = true

    # Show a CRT screen effect. Default is enabled.
    showcrt = false

    # Urls for social networks
    twitter = "https://twitter.com/theUkozi"
    linkedin = "https://www.linkedin.com/in/lucas-chumley/"
    github = "https://github.com/ukozi"

    # Enables or disables the loading animations. false activates them. Default is false.
    loadfastload = false

    # Sets the speed for the page loading effect. Default is 1.0.
    loadspeedfactor = 1.0

    # Enables or disables the second flyby cursor. Default is false.
    loadonepass = false

[params.copyright]
    name = "ukozi.com"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    url = "https://ukozi.com"

    # Text to go before copyright information
    prefix = "Compiled from fragments of the future for an audience stuck in the past."

    # Text to go between copyright and hugo disclaimer (if enabled)
    suffix = ""

[menu]
  # This displays buttons in the navbar to access your contents
  [[menu.main]]
    identifier = "about" # An unique identifier for the button
    name = "About"       # A display name for the button
    url = "/about/"      # The path to the content. It can lead to a single page (like here)
    weight = 10          # A number to order the buttons in the navbar

  [[menu.main]]
    identifier = "posts"
    name = "All posts"
    url = "/post/"       # The path can lead to a content folder too.
    weight = 20

[taxonomies]
category = "categories"
tag = "tags"


[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true